export const DICTIONARY = {
    BASE: {
        SCHEMA: "schema",
        NOTIFICATION: "notification",
        ID: "id",
        USER: "user",
        VIDEO: "video",
        PLAYLIST: "playlist",
        ORDERBY: "orderBy",
        PAGINATION: "pagination",
        URL: "url",
        TAGS: "TAGS",
        KEYWORDS: "keywords",
        EVENT: "event"
    },
    DATE: {
        CREATED_AT: "createAt",
        UPDATED_AT: "updatedAt"
    },
    PAGINATION:{
        SKIP: "skip",
        TAKE: "take",
        CURSOR: "cursor"
    },
    USER: {
        EMAIL: "email",
        NAME: "name",
        USER_ID: "userId",
        CREATEUSER: "createUser",
        GETUSER: "getUser",
        AUTH_USER: "authUser",
        SUBSCRIPTION: "subcription",
        UPDA_TEUSER: "updateUser",
        CHECKUSER: "checkUser",
        GET_SESSION: "getSession",
        UPDATETOKEN: "updateToken",
        SUBSCRIBER: "subscriber",
        ORDER_USERS: "orderUsers",
        DELETE: "deleteUser",
        USERNAME: "userName",
        PASSWORD: "password",
        SUBSCRIBER_ID: "subscriberId",
        SUBSCRIBER_IMAGE_URL: "subcriberImageUrl",
        PROFILE_IMAGE_URL: "profileImageUrl",
        RECIPIENT_USER_ID: "recipientUserId",
        RECIPIENT_USER_ARRAY_ID: "recipientUserArrayId",
    },
    EVENTS:[ "userCreated", "videoUploaded", "userSubscribed"],
    VIDEO: {
        TITLE: "title",
        VIEWS: "views",
        VIDEO_TITLE: "videoTitle",
        VIDEO_ID: "videoId",
        CREATE: "createVideo",
        GET_VIDEO: "getvideo",
        UPDATE_VIDEO:"updateVideo",
        CHANNEL: "getChannelVideos",
        GET_VIDEO_STATUS: "getVideoStatus",
        USER_VIDEO: "getVideoUserStatus",
        PAGINATION_ORDER: "paginationOrderVideos",
        GET_FAVORITE_VIDEOS: "getFavoriteVideos",
        FAVOURITE: "addFavouriteVideo",
        DELETE: "deleteVideo",
        AUTHOR_ID: "authorId",
        DESCRIPTION: "description",
        THUMBNAIL: "thumbnail",
        RATING: "rating",
    },
    CATEGORY:{
        CATEGORY_NAME: "categoryName",
        CATEGORY_ID: "categoryId"
    },
    TAG:{
        TAG_ID: "tagId",
        TAG_NAME: "tagName", 
    },
    NOTIFICATION: {
        NOTIFICATION_READ: "notificationRead",
        NOTIFICATION_STATUS: "notificationStatus",
        METADATA: "metadata",
        NOTIFICATION_ID: "notificationId",
        NOTIFICATION_ARRAY_ID: "notificationArrayId",
        NOTIFICATION_TITLE: "notificationTitle",
        CREATE_NOTIFICATION: "createNotification",
        UPDATE_NOTIFICATION: "updateNotification",
        GET_NOTIFICATION: "getNotification",
        DELETE_NOTIFICATION: "deleteNotification",
        GET_ALL_NOTIFICATION: "getAllNotifications",
        MARK_READ_NOTIFICATION: "markReadNotification",
        MARK_ALL_ALLREAD_NOTIFICATIONS: "markAllReadNotifications",
    },
    PLAYLIST: {
        CREATE_PLAYLIST: "createPalylist",
        DELETE_PLAYLIST: "deletePalylist",
        UPDATE_PALYLIST: "updatePlaylist",
        GET_PLAYLIST: "getPlaylist",
        GET_ALL_PLAYLIST: "getAllPlaylist",
        SHARE_PLAYLIST: "sharePlaylist",
    }
} as const